{{- if .Values.server.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hgi-vsx.fullname" . }}-storage
  labels:
    {{- include "hgi-vsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
{{- toYaml .Values.server.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.server.storage.size | quote }}
{{- if .Values.server.storage.storageClassName }}
  storageClassName: {{ .Values.server.storage.storageClassName | quote }}
{{- end }}
{{- end }}
