apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hgi-vsx.fullname" . }}-server-env
  labels:
    {{- include "hgi-vsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
{{- range $key, $value := .Values.server.secretEnv }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
