{{- if and .Values.proxy.tls.enabled .Values.proxy.tls.create (not .Values.proxy.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hgi-vsx.fullname" . }}-proxy-tls
  labels:
    {{- include "hgi-vsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
type: Opaque
stringData:
  nginx.crt: {{ .Values.proxy.tls.crt | quote }}
  nginx.key: {{ .Values.proxy.tls.key | quote }}
{{- end }}
