{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hgi-vsx.fullname" . }}-postgres
  labels:
    {{- include "hgi-vsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
  selector:
    {{- include "hgi-vsx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
