{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hgi-vsx.fullname" . }}-elasticsearch
  labels:
    {{- include "hgi-vsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
  selector:
    {{- include "hgi-vsx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
{{- end }}
