apiVersion: v1
kind: Service
metadata:
  name: {{ include "hgi-vsx.fullname" . }}-webui
  labels:
    {{- include "hgi-vsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.webui.service.port }}
      targetPort: http
  selector:
    {{- include "hgi-vsx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webui
